In [2]:
pip install numpy

In [4]:
import numpy as np

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])   #array

In [18]:
#RESHAPING - changing shape of an array i.e., no of elements in each demension
#reshaping 1D array to 2D array
newarr = arr.reshape(4, 3)   
print(newarr)

#reshaping array into unknown direction
newarr = arr.reshape(2,2,-1)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [20]:
#INDEXING - accessing an array element i.e., by referring to its index no.
#element at 0 index
print (arr[0])  

#additing of elements of 2nd index and 3rd index
print (arr[2]+arr[3])

1
7


In [22]:
#SLICING - taking element from one given index to another given index
#slice element from index 1 to index 5
print(arr[1:5])

#slice element from beginning to index 4(not included)
print(arr[:4])

[2 3 4 5]
[1 2 3 4]


In [23]:
#ITERATION - it means going through elements one by one
#1-d array
for x in arr:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [28]:
#iteration for 2d array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

#Iterate down to the scalars
for x in arr:
  for y in x:
    print(y)

[1 2 3]
[4 5 6]
1
2
3
4
5
6
